const productos = [
{
        id: 1,
        productName: "Bananas",
        price: 480,
        quanty: 1,
        img: "/client/media/bananas.png.png",
    },
    {
        id: 2,
        productName: "Leche",
        price: 950,
        quanty: 1,
        img: "cliente/media/leche.png.png",
    },
    {
        id: 3,
        productName: "Pollo",
        price: 750,
        quanty: 1,
        img: "cliente/media/pollo.png.png",
    },
    {
        id: 4,
        productName: "Mayonesa",
        price: 650,
        quanty: 1,
        img: "cliente/media/mayonesa.png.png",
    },
    {
        id: 5,
        productName: "Enlatados",
        price: 150,
        quanty: 1,
        img: "cliente/media/enlatados.png.png",
    },
    {
        id: 6,
        productName: "Varios",
        price: 850,
        quanty: 1,
        img: "cliente/media/varios.png.png",
    },
    ],
    
